---
name: 📊 Workflow Metrics

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "33 3 * * *" # Runs daily at 03:33 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  issues: write

jobs:
  metrics:
    runs-on: ubuntu-slim
    steps:
      - name: Collect Workflow Telemetry
        # yamllint disable-line rule:line-length
        uses: tsviz/actions-runner-telemetry@0fbec1ca185a193c94e4540e244110fdee912693 # v1.7.3
        with:
          enabled: ${{ vars.RUNNER_TELEMETRY_ENABLED || 'true' }}

      # yamllint disable-line rule:line-length
      - uses: yykamei/github-workflows-metrics@f79ad4a1ff5f537d85f8b132eb31846226d93f82 # v0.4.3
        with:
          only: pipeline.yml
          status: success
